### ISSUE TITLE
throw InvalidArgumentException is trying to find an exception from the local namespace

### ISSUE THREAD

**Issue by etorofiev** [esbenp/bruno#3]
See https://github.com/esbenp/laravel-controller/blob/master/src/EloquentBuilderTrait.php#L23

```
[2016-01-27 17:43:02] testing.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined function Optimus\Api\Controller\InvalidArg
umentException() in /vagrant/Code/api/vendor/optimus/laravel-controller/src/EloquentBuilderTrait.php:23
Stack trace:
#0 /vagrant/Code/api/vendor/optimus/eloquent/src/Repository.php(176): Optimus\Database\Eloquent\Repository->applyResourceOptions(Object(Illuminate\Database\Eloquent\
Builder), Array)
#1 /vagrant/Code/api/vendor/optimus/eloquent/src/Repository.php(104): Optimus\Database\Eloquent\Repository->createBaseBuilder(Array)
```

**Comment by esbenp** [comment]
Fixed https://github.com/esbenp/bruno/commit/7b1c3e634adc35696579818396dbb73d4ac4680b
